import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { Discover, Collection, Creators, Categories, NFC, Mooshrom, Works, Weeks } from "@/components/main";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-zinc-800">
        <div className="min-h-screen flex flex-col">
          <div className="flex-grow container mx-auto px-10">
            <Header />
            <main className="flex flex-col">
              <Discover />
              <Collection />
              <Creators />
              <Categories />
              <NFC />
              <Mooshrom />
              <Works />
              <Weeks />
            </main>
          </div>
          <footer className="bg-zinc-700 container mx-auto px-10">
            <Footer />
          </footer>
        </div>
      </body>
    </html>
  );
}
